### ISSUE TITLE
How can I use thermography_max or _min?

### ISSUE THREAD

**Issue by RI-SMJ** [seekthermal/seekcamera-python#11]
Dear, seekthermal
Thank you so much for providing a good source.
I have some questions to use seekcamera-opencv.py
I want to get maximum temperature of the frame with pixel coordinates, so I tried to use ' def thermography_max' of 'class SeekCameraFrameHeader' in camera.py.
However, I always get [160, 120, 0] values. 
If I use 'def thermography_spot' I got [160, 120, "estimated temperature value"] values. (estimated temperature value means the temperature of something like hot water, ice or human skin)

Is there a way to get the value what I want, by using "def thermography_max"? 
Or is there any other way to obtain the maximum temperature value where the seek-camera is filming?

**Comment by m-mead** [comment]
Hi @RI-SMJ, can you try outputting `SeekCameraFrameFormat.THERMOGRAPHY_FLOAT` in addition to the Display output (e.g. `SeekCameraFrameFormat.COLOR_ARGB8888`)? If you are only outputting Display output, I think just the spot temperature is outputted; I think Thermography output needs to be enabled to output the minimum and maximum temperatures.

```python
# Dual output of Display and Thermography output
camera.capture_session_start(
    SeekCameraFrameFormat.COLOR_ARGB888 | SeekCameraFrameFormat.THERMOGRAPHY_FLOAT
)
```

**Comment by RI-SMJ** [comment]
Oh, the problem is solved at once. Thank you so much.
