### ISSUE TITLE
Question: How can I load and display several Seek-Thermal Camera at the same time?

### ISSUE THREAD

**Issue by RI-SMJ** [seekthermal/seekcamera-python#17]
Dear, SeekThermal Team,
First of all, I sincerely thank you for providing a great source code.
I'm asking you a question because there are some difficulties in my current project.

- I want to connect several Seek Thermal Cameras (S304SP - more than two) to my computer and display and transmit them at the same time. Currently, video display and transmission (using an rtsp server) for one camera is possible, but only one recognition is possible even if 2 or more cameras are connected.
- How can I 2 cameras be recognized and display and transmitted?
I'm modifying the code based on "seekcamera-opencv.py". I want to print and transmit more than one screens based on OpenCV-Python.

Once again, thank you for providing a good code, and I would appreciate it if you could answer.
Thanks a lot!

**Comment by RI-SMJ** [comment]
I solved the problem by referring to #10.
So, I closed this question.
Thanks a lot.

**Comment by dgclq** [comment]
hello,  I have same question, and I can connect two camera but I don't know how to read the corresponding camera picture separately...
