### ISSUE TITLE
Does this support all models of seek camera? 

### ISSUE THREAD

**Issue by peng-ju** [seekthermal/seekcamera-python#30]
I am curious if this code support models like "Seek ShotPro", "Seek Thermal CompactPro"? Please provide a list of support models if it is possible. Thanks!

**Comment by tmullanix** [comment]
Hi. The Python wrapper sits on top of the Seek SDK. The SDK does not support any of the Seek Shot cameras. It does support the Compact series though (except potentially the Compact XR and some really older cameras).

**Comment by WDombrowski** [comment]
Unfortunately, the Seek Shot does not have any APIs or SDKs
