### ISSUE TITLE
    version = versions[-1]               ~~~~~~~~^^^^ IndexError: list index out of range

### ISSUE THREAD

**Issue by Salvantore** [seekthermal/seekcamera-python#31]
When I download and install Seek thermal SDK, and run the code I get this error, I don't know how to fix it, hope you can fix it for me

**Comment by tmullanix** [comment]
It looks like you don't have SEEKTHERMAL_LIB_DIR in your environment as noted in the "Other dependencies" section of the README.

**Comment by Salvantore** [comment]
What should I do to fix that error? I downloaded Seek_Thermal_SDK_4.4.2.20 and set up the path C:\Program Files\Seek Thermal\Seek Thermal SDK\Seek_Thermal_SDK_4.4.2.20\x64-windows\lib . I wonder if there is any way to fix the error version = versions[-1] ~~~~~~~~^^^^ IndexError: list index out of range? please let me know

**Comment by tmullanix** [comment]
While it looks like the "else" case could use a little clean-up, you are only getting there because the SEEKTHERMAL_LIB_DIR variable is not in the environment. Please open a new "command prompt" and type "set".  SEEKTHERMAL_LIB_DIR should be in the list.
 
![image](https://github.com/seekthermal/seekcamera-python/assets/83677988/929e2461-5e63-4ac4-9c64-694bea2bfb19)

**Comment by songucci1** [comment]
![image](https://github.com/seekthermal/seekcamera-python/assets/170646408/24a1b779-e22a-4338-a5db-8c4507cee816)
When I follow your instructions I get the error RuntimeError: Failed to load seekcamera.dll from C:\Program Files\Seek Thermal\Seek Thermal SDK\Seek_Thermal_SDK_4.4.2.20\x64-windows\lib\seekcamera.dll \seekcamera.dll

**Comment by tmullanix** [comment]
Is the Seek Thermal 4.4.2.20 SDK installed in c:\Program Files\Seek Thermal\Seek _Thermal_SDK?

**Comment by songucci1** [comment]
yes i have installed thermal camera sdk library
![image](https://github.com/seekthermal/seekcamera-python/assets/170646408/32495591-e87e-4611-bca7-502a73feca2a)

**Comment by tmullanix** [comment]
The env variable should not have seekcamera.dll in it. That automatically gets appended.


![env](https://github.com/seekthermal/seekcamera-python/assets/83677988/b553dad8-9eda-4afe-a7ba-49619fc57da3)

**Comment by songucci1** [comment]
I don't get what you mean. Can you show how to fix this error?

**Comment by songucci1** [comment]
I don't get what you mean. Can you show how to fix this error?

**Comment by tmullanix** [comment]
Set the env variable through Windows System Properties->Environment Variables. Select SEEKTHERMAL_LIB_DIR (or create it if you don't have one) and set it to the directory of the dll. Do not include the dll in the name though. Hit "OK" for all of these and then open a new command prompt to pick up the new variable.

![image](https://github.com/seekthermal/seekcamera-python/assets/83677988/f667f1b0-8196-4f40-b050-c3c9a9daeafe)

**Comment by songucci1** [comment]
Thank you. I did it

**Comment by tmullanix** [comment]
Great
