### ISSUE TITLE
Error when using the Example Script

### ISSUE THREAD

**Issue by DanSop** [seekthermal/seekcamera-python#32]
After installing the SDK to the required paths and running the seekcamera-simply.py I obtain the following error:

`python3 examples/seekcamera-simple.py`

```
CONNECT: E6D6090A1016
ERROR: E6D6090A1016
<class 'seekcamera.error.SeekCameraInvalidParameterError'>: E6D6090A1016
ERROR: E6D6090A1016
<class 'seekcamera.error.SeekCameraInvalidParameterError'>: E6D6090A1016
ERROR: E6D6090A1016
<class 'seekcamera.error.SeekCameraInvalidParameterError'>: E6D6090A1016
ERROR: E6D6090A1016
<class 'seekcamera.error.SeekCameraInvalidParameterError'>: E6D6090A1016
```

This error continues on forever. The camera is detected but only this error is shown. I am currently using Ubuntu 20.04 on an x86-64 system and I have installed the required SDK for my Linux distro.

I have also tested installing this on Windows and I obtain the same error after installing the drivers.

The examples built in C also give the same error.

I have tested this with both the S314RPX and the S304RP and they both produce a similar error.

**Comment by tmullanix** [comment]
1. Which camera are you trying to use?

2. Can you run the SDK's seekcamera-probe example? What does it output? Please make sure to use the pre-built examples in the SDK's bin directory and also try it on both Windows and your Ubuntu machines.

**Comment by DanSop** [comment]
Hello,
1. I am using the S314SPX Mosaic Core Starter Kit 320x240, 57HFOV, FF via a USB connection.
2. I am running the examples directly from the SDK folder via the bin directory. The output for the probe is the following:
```
seekcamera-probe starting
settings:
	1) mode (-m):          usb
	2) duration (-d):      1
+-------------------------------------------------------------------------+
| Seek Thermal SDK: 4.4.2.20                                              |
+-------------------------------------------------------------------------+
| CID          | SN           | CPN      | FW          | IO               |
+-------------------------------------------------------------------------+
| E6D6090A1016 | 1610Z151AAB9 | 2472X    | 14.25.0.4   | USB              |
|              |              |          |             | BUS: 1           |
|              |              |          |             | PORTS: 1         |
+-------------------------------------------------------------------------+
Window will close in 30 seconds
```
Trying this on Windows 10 (as well as my colleagues Window 11 machine) produced the same error when running the simple example. The probe output was also the same:

```
+-------------------------------------------------------------------------+
| Seek Thermal SDK: 4.4.2.20                                              |
+-------------------------------------------------------------------------+
| CID          | SN           | CPN      | FW          | IO               |
+-------------------------------------------------------------------------+
| E6D6090A1016 | 1610Z151AAB9 | 2472X    | 14.25.0.4   | USB              |
|              |              |          |             | BUS: 1           |
|              |              |          |             | PORTS: 4         |
+-------------------------------------------------------------------------+
Window will close in 30 seconds
```

**Comment by tmullanix** [comment]
Hmm... Well, the USB is communicating properly since the probe example returned what looks like valid information except the firmware looks incorrect. While I look into what the correct version should be, can you answer/do the following:

1. Has this Starter Kit ever worked for you? When (and from where) did you get it?

2. Can you try the Seek Simple Viewer (on Windows) and see if that can get an image? You can download it from developer.thermal.com. 

Todd

**Comment by DanSop** [comment]
I have three different kits that came from Digikey (acquired less than a year ago, the exact date is uncertain). The two "S304RP" kits have FW ver. 14.8.0.4 and the one "S314RPX" kit has FW ver. 14.25.0.4. Maybe it is due to the old FW?

All three of these kits do not show anything on the Seek Simple Viewer via Windows. New kits will be arriving in a week or so, therefore I will be testing new ones soon-ish.

Danny

**Comment by tmullanix** [comment]
That is the correct FW for the cores you are using. Note: initially you said a S314SPX...which is different from the cores you are using. Please let's continue this discussion on the Seek Developer Portal Ticket system (which I see you already have a ticket) since it is out of scope for this repo.
